### ISSUE TITLE
补充设计思路

### ISSUE THREAD

**Issue by yfwz100** [hh54188/Node-Simple-Cache#2]
这个算法讲解很到位，发现 wiki 可以编辑，于是补充了设计思路：

https://github.com/hh54188/Node-Simple-Cache/wiki/%E8%AE%BE%E8%AE%A1%E6%80%9D%E8%B7%AF

作者是否可以把设计思路放到 README.md 的链接中？

**Comment by xingchch** [comment]
因为单进程node 内存限制在2G 内存，所以这样的缓存设计是很不科学的．容易导致内存益处．且没有扩展性，(因为只能使用最多2G). 还是应该使用第三方的memche, 或redis服务来做缓存．
