### ISSUE TITLE
node 对内存使用有限制，如何破？

### ISSUE THREAD

**Issue by xingchch** [hh54188/Node-Simple-Cache#5]
node 对内存使用有限制，cache的数据不会超过１Ｇ，这个怎么破？？

**Comment by hh54188** [comment]
临时在google上搜了一个这个问题，这两个答案很有帮助

http://stackoverflow.com/questions/12779724/limiting-node-jss-memory-usage
http://stackoverflow.com/questions/7193959/memory-limit-in-node-js-and-chrome-v8

简单来说就是设置`max_old_space_size`，但对于64位机器来说，仍然存在上线1.7GB。更好的解决办法是，把你的程序开多个进行运行，因为1GB的限制是针对单个node进程

**Comment by xingchch** [comment]
@hh54188 
我后面也是这么想的，最简单的，起两个nodeserver , 将业务分到两个上面，前面nginx 做负载均衡．
